### ISSUE TITLE
Still being maintained

### ISSUE THREAD

**Issue by gino** [alexanderkhivrych/use-modal-hook#11]
Hi there,

I was wondering if this package is still being maintained. Since I am currently trying it out and seem to have some issues with using the hook. Not sure if this is still working.

Let me know if you still work on this, I could send the error, not quite sure why it's not working though.

I really like the concept of this hook, been looking for something like this for a long time. Also saw `react-modal-hook` before on npm but been having some little issues with that package unfortunately.

**Comment by alexanderkhivrych** [comment]
Hi, @gino, pls share the error message. I will take a look.

**Comment by gino** [comment]
I am trying to do the following, with Next.js:

```tsx
const MyModal = memo(
  ({ isOpen, onClose, title, description, closeBtnLabel }) => <div>test</div>
);

const Test = () => {
  const [showModal, hideModal] = useModal(MyModal);

  return (
    <div className="flex items-center justify-center min-h-screen">
      <div>
        <button onClick={showModal}>Show Modal</button>
      </div>
    </div>
  );
};

export default Test;
```

But I get the following error:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

**Comment by alexanderkhivrych** [comment]
@gino, could you run    npm ls react?

**Comment by gino** [comment]
@alexanderkhivrych, gave the following output:

```
-- use-modal-hook@1.0.18
  -- react@16.14.0 
```

But this project is just a fresh new [Next.js](https://nextjs.org/) scaffold, so not sure why this should cause issues.

**Comment by alexanderkhivrych** [comment]
ok, I will update react version tomorrow. Are u using react 17?

**Comment by gino** [comment]
Sounds good, and yeah I am:
```
"react": "17.0.1",
"react-dom": "17.0.1",
```

**Comment by alexanderkhivrych** [comment]
@gino try to use  version "1.0.19" with latest react and react-dom

**Comment by gino** [comment]
Hmmm, I seem to be having the same issue even though I am using `1.0.19`, the latest version as you mentioned. Could you try to reproduce my issue if you create a fresh Next.js application without configuring anything and just pull in the library, with the `create-next-app`. Since that's what I did and I can't use the hook with that method..

Let me know if you need any more information. Thanks.

**Comment by alexanderkhivrych** [comment]
@gino Maybe, you forgot to use ModalProvider? Actually, I was trying to run it with nextjs and it is fine.

**Comment by gino** [comment]
Thank you for this code example! I see. Hmm, looks strange. I will take a look at the code example again and try to fix it in my project, thanks a lot and I will let you know.

**Comment by gino** [comment]
I managed to fix the issue by upgrading both `react` and `react-dom` from `17.0.1` to `17.0.2`. Weird issue but fixed it, also used some parts of your code example. Thanks a lot, library works great!

**Comment by alexanderkhivrych** [comment]
@gino Ok, great!
