### ISSUE TITLE
Can't work with React 18

### ISSUE THREAD

**Issue by dev-techmoe** [alexanderkhivrych/use-modal-hook#15]
Error detail:

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```  

Here is a temporary solution for this problem use yarn according [this article](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)

1. add this json part below to your package.json
```
  "resolutions": {
    "use-modal-hook/react": "18.0.0",
    "use-modal-hook/react-dom": "18.0.0"
  },
```
2. run `yarn install`

**Comment by alexanderkhivrych** [comment]
@dev-techmoe Hi, I will make a major release on Wednesday with react 18 support.

**Comment by alexanderkhivrych** [comment]
Sorry, I was pretty busy. I will do it at weekends.

**Comment by alexanderkhivrych** [comment]
@dev-techmoe By the way, I use the node externals plugin, which will not include react to the bundle and use an external one. Are you sure you do not have another version of responding somewhere? Try to run this command npm ls react. However, I will publish a significant version soon.
